### ISSUE TITLE
About inference speed

### ISSUE THREAD

**Issue by Youjiangbaba** [researchmm/LightTrack#6]
Hello ,your work is very wonderful and testing in my video achieved a good  performance.  One frame inference time is  about 13ms  and ocean is about 15ms in 2080Ti.   How  to  raise the fps?     Thanks for your open-source codes and methods  and look forward your prompt reply.

**Comment by MasterBin-IIAU** [comment]
Hi, thanks for your appreciation to our work :)

First, about the speed on the Desktop GPUs (such as RTX 2080 Ti, RTX TITAN), the speed advantage of LightTrack to Ocean is not quite obvious, because the standard conv (especially 3x3 conv) is highly optimized and runs very fast on these platforms. However, the core operations of the LightTrack are 3x3 depth-wise conv and 1x1 conv. These operations run much slower than the standard 3x3 conv, although they have much less FLOPs. 

Second, about how to raise the FPS, we suggest using tools like ONNX or TensorRT to speed-up the inference.

**Comment by Youjiangbaba** [comment]
Ok,  I got it , thanks for your reply. Wish you a happy life!
