### ISSUE TITLE
移动端平台测试相关

### ISSUE THREAD

**Issue by wwn1233** [researchmm/LightTrack#7]
很不错的工作，支持； 另外想请教一下 在安卓平台部署的代码使用什么呢 可以分享学习实测一下吗？

**Comment by MasterBin-IIAU** [comment]
Thank you for your appreciation to our work :)
We tried two frameworks: [TNN](https://github.com/Tencent/TNN) and [onnxruntime](https://github.com/microsoft/onnxruntime). 
We use the former one to deploy our models on the mobile phones. 
But the latter one supports more operations than the former one.

**Comment by wwn1233** [comment]
> our

good。 But how to deploy the correlation operation in your model? Is it a custom op implemented by yourself?

**Comment by MasterBin-IIAU** [comment]
Hi, sorry for the late reply. In LightTrack, we use "pixel-wise correlation" to aggregate features of the template and the search region. We provide two types of implementations, one is by "convolution and for-loop" and the other is by "matrix multiplication". The second one runs much faster than the first one because the computation is quite vectorized. But some frameworks may not support the "matrix multiplication" operation. In this case, you can turn to use the first one (conv+for-loop). 

Thanks,
Bin

**Comment by wwn1233** [comment]
thanks！
